nelmio_api_doc:
    documentation:
        product_definitions:
            product:
                type: object
                properties:
                    sku:
                        type: string
                        required: true
                        description: product SKU
                        example: sku_123
                    type:
                        type: string
                        required: true
                        description: product type
                        example: SIMPLE-PRODUCT
                    templateId:
                        type: string
                        required: true
                        description: Template Id
                    categoryIds:
                        type: array
                        items:
                            type: string
                        required: false
                        description: Lista id kategorii
            product_update:
                type: object
                properties:
                    categoryIds:
                        type: array
                        items:
                            type: string
                        required: false
                        description: Lista id kategorii
            product_child:
                type: object
                properties:
                    child_id:
                        type: string
                        required: true
                        description: Product id
                        example: d1b9b64a-fef6-440c-9560-cf73daa4b4d6
            product_binding:
                type: object
                properties:
                    bind_id:
                        type: string
                        required: true
                        description: Multiselect attribute id
                        example: d1b9b64a-fef6-440c-9560-cf73daa4b4d6
            product_category:
                type: object
                properties:
                    category:
                        type: string
                        required: true
                        description: Category Id
                        example: d1b9b64a-fef6-440c-9560-cf73daa4b4d6
            attribute_values:
                type: object
                properties:
                    data:
                        type: array
                        required: true
                        items:
                            type: object
                            properties:
                                id:
                                    type: string
                                    required: true
                                    description: Product Id
                                    example: 9b0ceb29-26ac-4852-a602-6e5680a3a029
                                payload:
                                    type: array
                                    required: true
                                    items:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                required: true
                                                description: Attribute Id
                                                example: 789ff7ef-3a11-4b6a-ab25-3d262d2a78c3
                                            values:
                                                type: array
                                                required: true
                                                description: Attribute values per langauge
                                                items:
                                                    type: object
                                                    properties:
                                                        language:
                                                            type: string
                                                            required: true
                                                            example: en_GB
                                                        value:
                                                            type: string
                                                            required: true
                                                            description: Attribute value
                                                            example: test
