services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\AttributeDate\Application\:
        resource: '../../Application/*'

    Ergonode\AttributeDate\Application\Controller\Api\:
        resource: '../../Application/Controller/Api/*'
        tags: ['controller.service_arguments']

    Ergonode\AttributeDate\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject,Type}'

    Ergonode\AttributeDate\Infrastructure\:
        resource: '../../Infrastructure/*'
