services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\TranslationDeepl\Application\:
        resource: '../../Application/*'
        exclude: '../../Application/{DependencyInjection}'

    Ergonode\TranslationDeepl\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\TranslationDeepl\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\TranslationDeepl\Infrastructure\Provider\DeeplTranslationProvider:
        arguments:
            $deeplAuthKey: "%ergonode.translation_deepl.authentication_key%"

    Ergonode\TranslationDeepl\Infrastructure\Provider\UsageDeeplProvider:
        arguments:
            $deeplAuthKey: "%ergonode.translation_deepl.authentication_key%"

    Ergonode\TranslationDeepl\Infrastructure\Provider\TranslationProviderInterface: '@Ergonode\TranslationDeepl\Infrastructure\Provider\DeeplTranslationProvider'
    Ergonode\TranslationDeepl\Infrastructure\Provider\Decorator\CacheTranslationProviderDecorator:
        decorates: Ergonode\TranslationDeepl\Infrastructure\Provider\TranslationProviderInterface
        arguments:
            - '@Ergonode\TranslationDeepl\Infrastructure\Provider\Decorator\CacheTranslationProviderDecorator.inner'


    Ergonode\TranslationDeepl\Infrastructure\Provider\UsageDeeplProviderInterface: '@Ergonode\TranslationDeepl\Infrastructure\Provider\UsageDeeplProvider'
