services:
    Ergonode\Core\Test\Fixtures\Messenger\Transport\TestTransportFactory:
        arguments:
            $messageBus: '@messenger.bus.sync'
            $tokenStorage: '@security.token_storage'
        tags:
            - 'messenger.transport_factory'
