ergonode_condition_api:
    resource: '../../Application/Controller/Api/Condition/*'
    type: 'annotation'
    prefix: '/api/v1/{language}'

ergonode_condition_set_api:
    resource: '../../Application/Controller/Api/ConditionSet/*'
    type: 'annotation'
    prefix: '/api/v1/{language}'
