flysystem:
    storages:
        multimedia.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/multimedia'
        thumbnail.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/thumbnail'
