services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\ImporterErgonode\Application\:
        resource: '../../Application/*'

    Ergonode\ImporterErgonode\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity}'

    Ergonode\ImporterErgonode\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\ImporterErgonode\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\ImporterErgonode\Infrastructure\Reader\ErgonodeZipExtractor:
        arguments:
            $sourceDirectory: '%import_directory%'
            $destinationDirectory: '%import_directory%'

    Ergonode\ImporterErgonode\Infrastructure\Processor\ErgonodeImportProcess:
        arguments:
            $steps:
                - '@Ergonode\ImporterErgonode\Infrastructure\Processor\Step\ErgonodeCategoriesProcessorStep'
                - '@Ergonode\ImporterErgonode\Infrastructure\Processor\Step\ErgonodeTemplateProcessorStep'
#                - '@Ergonode\ImporterErgonode\Infrastructure\Processor\Step\ErgonodeOptionsProcessorStep'
#                - '@Ergonode\ImporterErgonode\Infrastructure\Processor\Step\ErgonodeAttributesProcessorStep'
#                - '@Ergonode\ImporterErgonode\Infrastructure\Processor\Step\ErgonodeMultimediaProcessorStep'
#                - '@Ergonode\ImporterErgonode\Infrastructure\Processor\Step\ErgonodeProductProcessorStep'