services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    Ergonode\Migration\Provider\MigrationDirectoryProvider:
        arguments:
            - '%kernel.project_dir%/../'
            - '@kernel'

    Ergonode\Migration\Provider\MigrationDirectoryProviderInterface: '@Ergonode\Migration\Provider\MigrationDirectoryProvider'

    Ergonode\Migration\Provider\MigrationConfigurationProvider:
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@Ergonode\Migration\Provider\MigrationDirectoryProviderInterface'

    Ergonode\Migration\Command\MigrateMigrationCommand:
        tags: ['console.command']
        arguments:
            - '@Ergonode\Migration\Provider\MigrationConfigurationProvider'

    Ergonode\Migration\Command\GenerateMigrationCommand:
        tags: ['console.command']
        arguments:
            - '@Ergonode\Migration\Provider\MigrationConfigurationProvider'
