services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ergonode\ExporterMagento2\Infrastructure\ExportProfile\Magento2ExportProfile:
    autowire: true

  Ergonode\ExporterMagento2\Domain\Factory\Magento2ExportCSVProfileFactory:
    autowire: true

  Ergonode\ExporterMagento2\Infrastructure\ExportProfile\Magento2ExportProfileValidatorStrategy:
    autowire: true
