services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Note\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\Note\Application\:
        resource: '../../Application/*'
        exclude: '../../Domain/{Model}'

    Ergonode\Note\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject}'

    Ergonode\Note\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Message}'

    Ergonode\Note\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\Note\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Note\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Note\Domain\Repository\NoteRepositoryInterface: '@Ergonode\Note\Persistence\Dbal\Repository\DbalNoteRepository'
    Ergonode\Note\Domain\Query\NoteQueryInterface: '@Ergonode\Note\Persistence\Dbal\Query\DbalNoteQuery'
