framework:
    messenger:
        transports:
            export: '%ergonode.exporter.messenger_transport%'
        routing:
            'Ergonode\Exporter\Domain\Command\Export\ProcessExportCommand': export
