services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Exporter\Application\:
        resource: '../../Application/*'

    Ergonode\Exporter\Application\Controller\Api\:
        resource: '../../Application/Controller/Api/*'
        tags: ['controller.service_arguments']

    Ergonode\Exporter\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\Exporter\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\Exporter\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\Exporter\Persistence\Dbal\Projector\:
        resource: '../../Persistence/Dbal/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\Exporter\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Exporter\Domain\Repository\ProductRepositoryInterface: '@Ergonode\Exporter\Persistence\Dbal\Repository\DbalProductRepository'
    Ergonode\Exporter\Domain\Repository\CategoryRepositoryInterface: '@Ergonode\Exporter\Persistence\Dbal\Repository\DbalCategoryRepository'
    Ergonode\Exporter\Domain\Repository\AttributeRepositoryInterface: '@Ergonode\Exporter\Persistence\Dbal\Repository\DbalAttributeRepository'
    Ergonode\Exporter\Domain\Repository\ExportProfileRepositoryInterface: '@Ergonode\Exporter\Persistence\Dbal\Repository\DbalExportProfileRepository'
    Ergonode\Exporter\Domain\Repository\TreeRepositoryInterface: '@Ergonode\Exporter\Persistence\Dbal\Repository\DbalTreeRepository'
    Ergonode\Exporter\Domain\Query\ExportProductQueryInterface: '@Ergonode\Exporter\Persistence\Dbal\Query\DbalExportProductQuery'
