services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Exporter\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\Exporter\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject}'

    Ergonode\Exporter\Persistence\Dbal\Projector\:
        resource: '../../Persistence/Dbal/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\Exporter\Domain\Repository\ProductRepositoryInterface: '@Ergonode\Exporter\Persistence\Dbal\Repository\DbalProductRepository'
    Ergonode\Exporter\Domain\Repository\CategoryRepositoryInterface: '@Ergonode\Exporter\Persistence\Dbal\Repository\DbalCategoryRepository'
