services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Exporter\Application\:
        resource: '../../Application/*'

    Ergonode\Exporter\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\Exporter\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\Exporter\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Exporter\Infrastructure\Handler\Export\DeleteExportCommandHandler:
        tags: [{name: 'messenger.message_handler', priority: -10}]
