services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Exporter\Application\:
        resource: '../../Application/*'

    Ergonode\Exporter\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\Exporter\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\Exporter\Infrastructure\Persistence\Projector\:
        resource: '../../Infrastructure/Persistence/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\Exporter\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Exporter\Domain\Repository\ProductRepositoryInterface: '@Ergonode\Exporter\Infrastructure\Persistence\Repository\DbalProductRepository'
    Ergonode\Exporter\Domain\Repository\CategoryRepositoryInterface: '@Ergonode\Exporter\Infrastructure\Persistence\Repository\DbalCategoryRepository'
    Ergonode\Exporter\Domain\Repository\AttributeRepositoryInterface: '@Ergonode\Exporter\Infrastructure\Persistence\Repository\DbalAttributeRepository'
    Ergonode\Exporter\Domain\Repository\TreeRepositoryInterface: '@Ergonode\Exporter\Infrastructure\Persistence\Repository\DbalTreeRepository'
    Ergonode\Exporter\Domain\Query\ExportProductQueryInterface: '@Ergonode\Exporter\Infrastructure\Persistence\Query\DbalExportProductQuery'
