services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Exporter\Application\:
        resource: '../../Application/*'

    Ergonode\Exporter\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\Exporter\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\Exporter\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Exporter\Infrastructure\Provider\RemoveExportArtifactsCommandFactoryProvider:
        arguments:
            - !tagged_iterator 'export.remove_export_artifacts_command_factory_interface'
