services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Attribute\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\Attribute\Application\:
        resource: '../../Application/*'

    Ergonode\Attribute\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\Attribute\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject,Type}'

    Ergonode\Attribute\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Handler,JMS}'

    Ergonode\Attribute\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Attribute\Persistence\Dbal\Projector\:
        resource: '../../Persistence/Dbal/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\Attribute\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Attribute\Infrastructure\JMS\Serializer\Handler\OptionInterfaceHandler:
        calls:
            - ['set', ['Ergonode\Attribute\Domain\ValueObject\OptionValue\StringOption']]
            - ['set', ['Ergonode\Attribute\Domain\ValueObject\OptionValue\MultilingualOption']]

    Ergonode\Attribute\Domain\Repository\AttributeRepositoryInterface: '@Ergonode\Attribute\Persistence\Dbal\Repository\DbalAttributeRepository'
#    Ergonode\Attribute\Persistence\Dbal\Repository\Decorator\CacheAttributeRepositoryDecorator:
#        decorates: Ergonode\Attribute\Domain\Repository\AttributeRepositoryInterface
#        arguments:
#            - '@Ergonode\Attribute\Persistence\Dbal\Repository\Decorator\CacheAttributeRepositoryDecorator.inner'
    Ergonode\Attribute\Domain\Repository\AttributeGroupRepositoryInterface: '@Ergonode\Attribute\Persistence\Dbal\Repository\DbalAttributeGroupRepository'

    Ergonode\Attribute\Domain\Query\AttributeQueryInterface: '@Ergonode\Attribute\Persistence\Dbal\Query\DbalAttributeQuery'
    Ergonode\Attribute\Persistence\Dbal\Query\Decorator\CacheAttributeQueryDecorator:
        decorates: Ergonode\Attribute\Domain\Query\AttributeQueryInterface
        arguments:
            - '@Ergonode\Attribute\Persistence\Dbal\Query\Decorator\CacheAttributeQueryDecorator.inner'
    Ergonode\Attribute\Domain\Query\AttributeGroupQueryInterface: '@Ergonode\Attribute\Persistence\Dbal\Query\DbalAttributeGroupQuery'
    Ergonode\Attribute\Domain\Query\AttributeGridQueryInterface: '@Ergonode\Attribute\Persistence\Dbal\Query\DbalAttributeGridQuery'
    Ergonode\Attribute\Domain\Query\CurrencyQueryInterface: '@Ergonode\Attribute\Persistence\Dbal\Query\DbalCurrencyQuery'
    Ergonode\Attribute\Domain\Query\UnitQueryInterface: '@Ergonode\Attribute\Persistence\Dbal\Query\DbalUnitQuery'

    Ergonode\Attribute\Application\Provider\AttributePropertyFormResolver:
        calls:
            - ['set', ['PRICE','Ergonode\Attribute\Application\Form\Property\PriceAttributePropertyForm']]
            - ['set', ['DATE','Ergonode\Attribute\Application\Form\Property\DateAttributePropertyForm']]
            - ['set', ['UNIT','Ergonode\Attribute\Application\Form\Property\UnitAttributePropertyForm']]