services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Attribute\Application\:
        resource: '../../Application/*'

    Ergonode\Attribute\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\Attribute\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject,Type}'

    Ergonode\Attribute\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Handler,JMS}'

    Ergonode\Attribute\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Attribute\Infrastructure\Persistence\Projector\:
        resource: '../../Infrastructure/Persistence/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\Attribute\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Attribute\Infrastructure\JMS\Serializer\Handler\OptionInterfaceHandler:
        calls:
            - ['set', ['Ergonode\Attribute\Domain\ValueObject\OptionValue\StringOption']]
            - ['set', ['Ergonode\Attribute\Domain\ValueObject\OptionValue\MultilingualOption']]

    Ergonode\Attribute\Domain\Repository\AttributeRepositoryInterface: '@Ergonode\Attribute\Infrastructure\Persistence\Repository\DbalAttributeRepository'
#    Ergonode\Attribute\Infrastructure\Persistence\Repository\Decorator\CacheAttributeRepositoryDecorator:
#        decorates: Ergonode\Attribute\Domain\Repository\AttributeRepositoryInterface
#        arguments:
#            - '@Ergonode\Attribute\Infrastructure\Persistence\Repository\Decorator\CacheAttributeRepositoryDecorator.inner'
    Ergonode\Attribute\Domain\Repository\AttributeGroupRepositoryInterface: '@Ergonode\Attribute\Infrastructure\Persistence\Repository\DbalAttributeGroupRepository'

    Ergonode\Attribute\Domain\Query\AttributeQueryInterface: '@Ergonode\Attribute\Infrastructure\Persistence\Query\DbalAttributeQuery'
    Ergonode\Attribute\Infrastructure\Persistence\Query\Decorator\CacheAttributeQueryDecorator:
        decorates: Ergonode\Attribute\Domain\Query\AttributeQueryInterface
        arguments:
            - '@Ergonode\Attribute\Infrastructure\Persistence\Query\Decorator\CacheAttributeQueryDecorator.inner'
    Ergonode\Attribute\Domain\Query\AttributeGroupQueryInterface: '@Ergonode\Attribute\Infrastructure\Persistence\Query\DbalAttributeGroupQuery'
    Ergonode\Attribute\Domain\Query\AttributeGridQueryInterface: '@Ergonode\Attribute\Infrastructure\Persistence\Query\DbalAttributeGridQuery'
    Ergonode\Attribute\Domain\Query\CurrencyQueryInterface: '@Ergonode\Attribute\Infrastructure\Persistence\Query\DbalCurrencyQuery'

    Ergonode\Attribute\Application\Provider\AttributePropertyFormResolver:
        calls:
            - ['set', ['PRICE','Ergonode\Attribute\Application\Form\Attribute\Configuration\PriceAttributeConfigurationForm']]
            - ['set', ['DATE','Ergonode\Attribute\Application\Form\Attribute\Configuration\DateAttributeConfigurationForm']]
            - ['set', ['UNIT','Ergonode\Attribute\Application\Form\Attribute\Configuration\UnitAttributeConfigurationForm']]

    Ergonode\Attribute\Infrastructure\Mapper\AttributeValueMapper:
        arguments:
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\NumericAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\SelectAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\MultiSelectAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\PriceAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\UnitAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\TextAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\TextareaAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\GalleryAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\FileAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\ImageAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\DateAttributeMapperStrategy'
            - '@Ergonode\Attribute\Infrastructure\Mapper\Strategy\StatusAttributeMapperStrategy'