services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\CategoryTree\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\CategoryTree\Application\:
        resource: '../../Application/*'
        exclude: '../../Domain/{Model}'

    Ergonode\CategoryTree\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject}'

    Ergonode\CategoryTree\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Message}'

    Ergonode\CategoryTree\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\CategoryTree\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\CategoryTree\Persistence\Dbal\Projector\:
        resource: '../../Persistence/Dbal/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\CategoryTree\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\CategoryTree\Domain\Repository\TreeRepositoryInterface: '@Ergonode\CategoryTree\Persistence\Dbal\Repository\DbalTreeRepository'
    Ergonode\CategoryTree\Domain\Query\TreeQueryInterface: '@Ergonode\CategoryTree\Persistence\Dbal\Query\DbalTreeQuery'

