framework:
    messenger:
        routing:
            Ergonode\Designer\Domain\Command\CreateTemplateCommand: '%ergonode.designer.messenger_transport_name%'
            Ergonode\Designer\Domain\Command\UpdateTemplateCommand: '%ergonode.designer.messenger_transport_name%'
