Ergonode\Importer\Infrastructure\Converter\ConverterInterface:
    discriminator_map:
        type_property: 'type'
        mapping:
            text: Ergonode\Importer\Infrastructure\Converter\TextConverter
            join: Ergonode\Importer\Infrastructure\Converter\JoinConverter
            slug: Ergonode\Importer\Infrastructure\Converter\SlugConverter
            const: Ergonode\Importer\Infrastructure\Converter\ConstConverter
            multilingual_text: Ergonode\Importer\Infrastructure\Converter\MultilingualTextConverter
            date: Ergonode\Importer\Infrastructure\Converter\DateConverter
            mapping: Ergonode\Importer\Infrastructure\Converter\MappingConverter
