<?php

/**
 * Copyright © Bold Brand Commerce Sp. z o.o. All rights reserved.
 * See LICENSE.txt for license details.
 */

declare(strict_types = 1);

namespace Ergonode\Generator\Builder\Domain\Entity;

use Ergonode\Generator\Builder\BuilderInterface;
use Ergonode\Generator\Builder\FileBuilder;
use Ergonode\SharedKernel\Domain\AggregateId;
use Nette\PhpGenerator\PhpFile;

/**
 */
class EntityIdClassBuilder implements BuilderInterface
{
    /**
     * @var FileBuilder
     */
    private FileBuilder $builder;

    /**
     * @param FileBuilder $builder
     */
    public function __construct(FileBuilder $builder)
    {
        $this->builder = $builder;
    }

    /**
     * @param string $module
     * @param string $entityName
     * @param array  $properties
     *
     * @return PhpFile
     */
    public function build(string $module, string $entityName, array $properties = []): PhpFile
    {
        $file = $this->builder->build();
        $className = sprintf('%sId', $entityName);

        $namespace = sprintf('Ergonode\%s\Domain\Entity', ucfirst($module));

        $phpNamespace = $file->addNamespace($namespace);

        $class = $phpNamespace->addClass($className);
        $class->addExtend(AggregateId::class);
        $class->addComment('Autogenerated class');

        return $file;
    }
}
