services:
    ergonode.new_relic.event_subscriber.messenger:
        class: Ergonode\NewRelic\Application\EventSubscriber\MessengerEventSubscriber
        arguments:
            $newRelic: '@ergonode.new_relic.new_relic'
        tags: ['kernel.event_subscriber']
