parameters:
    authorization_header: 'JWTAuthorization'

services:
    Ergonode\Authentication\Test\Behat\Service\RequestAuthenticator:
        $JWTTokenManager: '@lexik_jwt_authentication.jwt_manager'
        $authorizationHeader: '%authorization_header%'
