services:
    _defaults:
        autoconfigure: true

    Ergonode\Authentication\Test\Behat\Service\RequestAuthenticator:
        arguments:
            $JWTTokenManager: '@lexik_jwt_authentication.jwt_manager'
            $authorizationHeader: '%authorization_header%'
        public: true

    Ergonode\Core\Test\Fixtures\Messenger\Transport\TestTransportFactory:
        arguments:
            $messageBus: '@messenger.bus.sync'
            $tokenStorage: '@security.token_storage'
        tags:
            - 'messenger.transport_factory'

    Ergonode\Core\Test\Behat\Context\UserContext:
        $userProvider: '@Ergonode\Authentication\Application\Security\Provider\EmailUserProvider'

    Ergonode\Core\Test\Behat\Context\ApiAuthContext:
        $authenticator: '@Ergonode\Authentication\Test\Behat\Service\RequestAuthenticator'
        $container: '@service_container'

    Ergonode\Core\Test\Behat\Context\ApiAuthTokenContext:
        $authHeader: '%authorization_header%'
        $container: '@service_container'

    Ergonode\Core\Test\Behat\Context\AuthenticationContext:
        $username: 'test@ergonode.com'
        $password: 'abcd1234'

    Ergonode\Core\Test\TestDownloaderDecorator:
        decorates: Ergonode\Core\Infrastructure\Service\DownloaderInterface
        decoration_priority: -100
        arguments:
            $kernel: '@kernel'
            $downloader: '@Ergonode\Core\Test\TestDownloaderDecorator.inner'
