services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Authentication\Application\Security\:
        resource: '../../Application/Security/*'

    Ergonode\Authentication\Application\Middleware\:
        resource: '../../Application/Middleware/*'
