services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Authentication\Application\Security\:
        resource: '../../Application/Security/*'

    Ergonode\Authentication\Application\Middleware\:
        resource: '../../Application/Middleware/*'

    Ergonode\Authentication\Application\Stamp\:
        resource: '../../Application/Stamp/*'

    Ergonode\Authentication\Application\Token\:
        resource: '../../Application/Token/*'
