services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Authentication\Application\Security\:
        resource: '../../Application/Security/*'

    Ergonode\Authentication\Application\Middleware\:
        resource: '../../Application/Middleware/*'

    Ergonode\Authentication\Application\RefreshToken\Doctrine\Mapping\RefreshTokenMetadataFactory: ~
    Ergonode\Authentication\Application\RefreshToken\Doctrine\RefreshTokenManager: ~
    Ergonode\Authentication\Infrastructure\Persistence\DbalRefreshTokenRepository: ~
    Ergonode\Authentication\Application\RefreshToken\Doctrine\RefreshTokenRepositoryInterface: '@Ergonode\Authentication\Infrastructure\Persistence\DbalRefreshTokenRepository'
