services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\ExporterMagento2\Application\:
        resource: '../../Application/*'

    Ergonode\ExporterMagento2\Domain\:
        resource: '../../Domain/*'

    Ergonode\ExporterMagento2\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\ExporterMagento2\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']
