services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Ergonode\ImporterMagento1\Application\:
        resource: '../../Application/*'

    Ergonode\ImporterMagento1\Domain\:
      resource: '../../Domain/*'
      exclude: '../../Domain/{Entity}'

    Ergonode\ImporterMagento1\Infrastructure\:
      resource: '../../Infrastructure/*'

    Ergonode\ImporterMagento1\Infrastructure\Reader\Magento1CsvReader:
      arguments:
        $directory: '%import_directory%'

    Ergonode\ImporterMagento1\Infrastructure\Processor\StartMagento1ImportProcess:
      arguments:
        $steps:
          - '@Ergonode\ImporterMagento1\Infrastructure\Processor\Step\Magento1TemplateProcessor'
#          - '@Ergonode\ImporterMagento1\Infrastructure\Processor\Step\Magento1MultimediaProcessor'
          - '@Ergonode\ImporterMagento1\Infrastructure\Processor\Step\Magento1CategoryProcessor'
          - '@Ergonode\ImporterMagento1\Infrastructure\Processor\Step\Magento1AttributeProcessor'
          - '@Ergonode\ImporterMagento1\Infrastructure\Processor\Step\Magento1ProductProcessor'
