nelmio_api_doc:
    documentation:
        product_collection_definitions:
            product_collection_create:
                type: object
                properties:
                    code:
                        type: string
                        description: Product collection code
                        required: true
                        example: product_collection_code_1
                    name:
                        type: object
                        description: Product Collection name
                        example:
                            de_DE: Name DE
                            en_GB: Name EN
                    description:
                        type: object
                        description: Product Collection description
                        example:
                            de_DE: Description DE
                            en_GB: Description EN
                    typeId:
                        type: string
                        description: Product Collection Type Id
                        required: true
                        example: 21eca257-78ed-54ed-936e-ff6823a87da7
            product_collection_update:
                type: object
                properties:
                    name:
                        type: object
                        description: Product Collection name
                        example:
                            de_DE: Name DE
                            en_GB: Name EN
                    description:
                        type: object
                        description: Product Collection description
                        example:
                            de_DE: Description DE
                            en_GB: Description EN
                    typeId:
                        type: string
                        description: Product Collection Type Id
                        required: true
                        example: ccd5c2b5-da15-4bd2-a476-bfa689560f22
            element_create:
                type: object
                properties:
                    productId:
                        type: string
                        description: Product Id
                        required: true
                        example: ccd5c2b5-da15-4bd2-a476-bfa689560f22
                    visible:
                        type: bool
                        required: true
                        description: Show if product is visible for other products from collection
                        example: true
            element_update:
                type: object
                properties:
                    visible:
                        type: bool
                        required: true
                        description: Show if product is visible for other products from collection
                        example: true

            element_create_by_segment_and_sku:
                type: object
                properties:
                    segments:
                        type: array
                        items:
                            type: string
                        required: false
                        description: List of segment Ids
                        example:
                            [ a4898f22-bcca-5842-bc78-b2401191cea8, 1bdcab91-5fc1-42c0-8a7f-4602ca9a2511]
                    skus:
                        type: array
                        items:
                            type: string
                        required: false
                        description: List of Skus
                        example:
                            [ SKU_1, SKU_2]


            product_collection_type_create:
                type: object
                properties:
                    code:
                        type: string
                        description: Product collection type code
                        required: true
                        example: product_collection_type_code_1
                    name:
                        type: object
                        description: Product Collection type name
                        example:
                            de_DE: Name DE
                            en_GB: Name EN
            product_collection_type_update:
                type: object
                properties:
                    name:
                        type: object
                        description: Product Collection type name
                        example:
                            de_DE: Name DE
                            en_GB: Name EN
