services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Ergonode\ProductCollection\Application\:
        resource: '../../Application/*'
        exclude: '../../Application/{DependencyInjection}'
    
    Ergonode\ProductCollection\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject}'
    
    Ergonode\ProductCollection\Infrastructure\:
        resource: '../../Infrastructure/*'
    
    Ergonode\ProductCollection\Persistence\:
        resource: '../../Persistence/*'
    
    Ergonode\ProductCollection\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']
    
    Ergonode\ProductCollection\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']
    
    Ergonode\ProductCollection\Persistence\Dbal\Projector\:
        resource: '../../Persistence/Dbal/Projector/*'
        tags: ['messenger.message_handler']
    
    Ergonode\ProductCollection\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']
    
    Ergonode\ProductCollection\Domain\Repository\ProductCollectionRepositoryInterface: '@Ergonode\ProductCollection\Persistence\Dbal\Repository\DbalProductCollectionRepository'
    Ergonode\ProductCollection\Domain\Repository\ProductCollectionTypeRepositoryInterface: '@Ergonode\ProductCollection\Persistence\Dbal\Repository\DbalProductCollectionTypeRepository'
    Ergonode\ProductCollection\Domain\Query\ProductCollectionQueryInterface: '@Ergonode\ProductCollection\Persistence\Dbal\Query\DbalProductCollectionQuery'
    Ergonode\ProductCollection\Domain\Query\ProductCollectionElementQueryInterface: '@Ergonode\ProductCollection\Persistence\Dbal\Query\DbalProductCollectionElementQuery'
    Ergonode\ProductCollection\Domain\Query\ProductCollectionTypeQueryInterface: '@Ergonode\ProductCollection\Persistence\Dbal\Query\DbalProductCollectionTypeQuery'
