services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Ergonode\ProductCollection\Application\:
        resource: '../../Application/*'
        exclude: '../../Application/{DependencyInjection}'
    
    Ergonode\ProductCollection\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject}'
    
    Ergonode\ProductCollection\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\ProductCollection\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']
    
    Ergonode\ProductCollection\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']
    
    Ergonode\ProductCollection\Infrastructure\Persistence\Projector\:
        resource: '../../Infrastructure/Persistence/Projector/*'
        tags: ['ergonode.event_sourcing.projector']

    Ergonode\ProductCollection\Domain\Repository\ProductCollectionRepositoryInterface: '@Ergonode\ProductCollection\Infrastructure\Persistence\Repository\EventStoreProductCollectionRepository'
    Ergonode\ProductCollection\Domain\Repository\ProductCollectionTypeRepositoryInterface: '@Ergonode\ProductCollection\Infrastructure\Persistence\Repository\EventStoreProductCollectionTypeRepository'

    Ergonode\ProductCollection\Domain\Query\ProductCollectionQueryInterface: '@Ergonode\ProductCollection\Infrastructure\Persistence\Query\DbalProductCollectionQuery'
    Ergonode\ProductCollection\Domain\Query\ProductCollectionGridQueryInterface: '@Ergonode\ProductCollection\Infrastructure\Persistence\Query\DbalProductCollectionGridQuery'
    Ergonode\ProductCollection\Domain\Query\ProductCollectionElementGridQueryInterface: '@Ergonode\ProductCollection\Infrastructure\Persistence\Query\DbalProductCollectionElementGridQuery'
    Ergonode\ProductCollection\Domain\Query\ProductCollectionTypeQueryInterface: '@Ergonode\ProductCollection\Infrastructure\Persistence\Query\DbalProductCollectionTypeQuery'
    Ergonode\ProductCollection\Domain\Query\ProductCollectionTypeGridQueryInterface: '@Ergonode\ProductCollection\Infrastructure\Persistence\Query\DbalProductCollectionTypeGridQuery'
    Ergonode\ProductCollection\Domain\Query\ProductProductCollectionGridQueryInterface: '@Ergonode\ProductCollection\Infrastructure\Persistence\Query\DbalProductProductCollectionGridQuery'
