<?php

/**
 * Copyright © Bold Brand Commerce Sp. z o.o. All rights reserved.
 * See LICENSE.txt for license details.
 */

declare(strict_types = 1);

namespace Ergonode\Generator\Builder\Domain\Repository;

use Ergonode\Generator\Builder\BuilderInterface;
use Ergonode\Generator\Builder\FileBuilder;
use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\PhpFile;

/**
 */
class EntityRepositoryInterfaceBuilder implements BuilderInterface
{
    /**
     * @var FileBuilder
     */
    private $builder;

    /**
     * @param FileBuilder $builder
     */
    public function __construct(FileBuilder $builder)
    {
        $this->builder = $builder;
    }

    /**
     * @param string $module
     * @param string $entity
     *
     * @return PhpFile
     */
    public function build(string $module, string $entity): PhpFile
    {
        $file = $this->builder->build();
        $interfaceName = sprintf('%sRepositoryInterface', $entity);

        $namespace = sprintf('Ergonode\%s\Domain\Repository', ucfirst($module));

        $phpNamespace = $file->addNamespace($namespace);
        $phpNamespace->addUse(sprintf('Ergonode\%s\Domain\Entity\%s', ucfirst($module), $entity));
        $phpNamespace->addUse(sprintf('Ergonode\%s\Domain\Entity\%sId', ucfirst($module), $entity));

        $phpClass = $phpNamespace->addInterface($interfaceName);
        $phpClass->addComment('Autogenerated interface');
        $phpClass->addMethod('load')
            ->setReturnType(sprintf('Ergonode\%s\Domain\Entity\%s', ucfirst($module), $entity))
            ->setReturnNullable()
            ->setVisibility(ClassType::VISIBILITY_PUBLIC)
            ->addComment(sprintf('@param %sId $id', $entity))
            ->addComment('')
            ->addComment(sprintf('@return %s', $entity))
            ->addParameter('id')
            ->setTypeHint(sprintf('Ergonode\%s\Domain\Entity\%sId', ucfirst($module), $entity));
        $phpClass->addMethod('save')
            ->setReturnType('void')
            ->setVisibility(ClassType::VISIBILITY_PUBLIC)
            ->addComment(sprintf('@param %s $object', $entity))
            ->addParameter('object')
            ->setTypeHint(sprintf('Ergonode\%s\Domain\Entity\%s', ucfirst($module), $entity));
        $phpClass->addMethod('exists')
            ->setReturnType('bool')
            ->setVisibility(ClassType::VISIBILITY_PUBLIC)
            ->addComment(sprintf('@param %sId $id', $entity))
            ->addComment('')
            ->addComment('@return bool')
            ->addParameter('id')
            ->setTypeHint(sprintf('Ergonode\%s\Domain\Entity\%sId', ucfirst($module), $entity));

        return $file;
    }
}
