nelmio_api_doc:
    documentation:
        channel_definitions:
            channel:
                type: 'object'
                properties:
                    type:
                        type: string
                        required: true
                        description: name
                        example: channel1
            scheduler:
                type: 'object'
                properties:
                    active:
                        type: boolean
                        required: true
                    start:
                        type: string
                        required: true
                        example: 2020-09-22T11:42:30+02:00
                    hour:
                        type: integer
                        required: true
                    minute:
                        type: integer
                        required: true
