Ergonode\Workflow\Domain\Condition\WorkflowConditionInterface:
    discriminator_map:
        type_property: 'type'
        mapping:
            ATTRIBUTE_EXISTS_WORKFLOW_CONDITION: Ergonode\Workflow\Domain\Condition\AttributeExistsWorkflowCondition