services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\ExporterFile\Application\:
        resource: '../../Application/*'

    Ergonode\ExporterFile\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\ExporterFile\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\ExporterFile\Infrastructure\Processor\Strategy\Template\:
        resource: '../../Infrastructure/Processor/Strategy/Template/*'
        tags: ['export-file.template_element_map_interface']

    Ergonode\ExporterFile\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\ExporterFile\Infrastructure\Handler\ProcessExportCommandHandler:
        tags: ['messenger.message_handler']
        arguments:
            $steps:
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\AttributeExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\OptionExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\CategoryExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\ProductExportProcessStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\MultimediaExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\TemplateExportProcessorStep'

    Ergonode\ExporterFile\Infrastructure\Processor\Strategy\TemplateElementMapProvider:
       arguments:
           $strategies: !tagged_iterator 'export-file.template_element_map_interface'
