services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\ExporterFile\Application\:
        resource: '../../Application/*'

    Ergonode\ExporterFile\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\ExporterFile\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\ExporterFile\Infrastructure\Builder\Template\:
        resource: '../../Infrastructure/Builder/Template/*'
        tags: ['export-file.template_element_builder']

    Ergonode\ExporterFile\Infrastructure\Builder\Product\:
        resource: '../../Infrastructure/Builder/Product/*'
        tags: ['export-file.product_builder']

    Ergonode\ExporterFile\Infrastructure\Builder\Attribute\:
        resource: '../../Infrastructure/Builder/Attribute/*'
        tags: ['export-file.attribute_builder']

    Ergonode\ExporterFile\Infrastructure\Builder\Option\:
        resource: '../../Infrastructure/Builder/Option/*'
        tags: ['export-file.option_builder']

    Ergonode\ExporterFile\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\ExporterFile\Infrastructure\Processor\Step\:
        resource: '../../Infrastructure/Processor/Step/*'
        tags: ['export-file.steps_process']

    Ergonode\ExporterFile\Infrastructure\Handler\Export\StartProcessCommandHandler:
        tags: ['messenger.message_handler']
        arguments:
            $builders: !tagged_iterator 'export-file.header_builder'

    Ergonode\ExporterFile\Infrastructure\Handler\ProcessExportCommandHandler:
        tags: ['messenger.message_handler']
        arguments:
            $steps: !tagged_iterator 'export-file.steps_process'

    Ergonode\ExporterFile\Infrastructure\Builder\ExportTemplateBuilder:
        tags: ['export-file.header_builder']
        arguments:
            $builders: !tagged_iterator 'export-file.template_builder'

    Ergonode\ExporterFile\Infrastructure\Builder\ExportTemplateElementBuilder:
        tags: ['export-file.header_builder']
        arguments:
            $builders: !tagged_iterator 'export-file.template_element_builder'

    Ergonode\ExporterFile\Infrastructure\Builder\ExportProductBuilder:
        tags: ['export-file.header_builder']
        arguments:
            $builders: !tagged_iterator 'export-file.product_builder'

    Ergonode\ExporterFile\Infrastructure\Builder\ExportCategoryBuilder:
        tags: ['export-file.header_builder']
        arguments:
            $builders: !tagged_iterator 'export-file.category_builder'

    Ergonode\ExporterFile\Infrastructure\Builder\ExportAttributeBuilder:
        tags: ['export-file.header_builder']
        arguments:
            $builders: !tagged_iterator 'export-file.attribute_builder'

    Ergonode\ExporterFile\Infrastructure\Builder\ExportOptionBuilder:
        tags: ['export-file.header_builder']
        arguments:
            $builders: !tagged_iterator 'export-file.option_builder'
