services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\ExporterFile\Application\:
        resource: '../../Application/*'

#    Ergonode\ExporterFile\Application\Controller\Api\:
#        resource: '../../Application/Controller/Api/*'
#        tags: ['controller.service_arguments']

    Ergonode\ExporterFile\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\ExporterFile\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

#    Ergonode\ExporterFile\Persistence\:
#        resource: '../../Persistence/*'

    Ergonode\ExporterFile\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

#    Ergonode\ExporterFile\Persistence\Dbal\Projector\:
#        resource: '../../Persistence/Dbal/Projector/*'
#        tags: ['messenger.message_handler']

    Ergonode\ExporterFile\Infrastructure\Handler\ProcessExportCommandHandler:
        tags: ['messenger.message_handler']
        arguments:
            $steps:
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\AttributeExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\OptionExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\CategoryExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\ProductExportProcessStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\MultimediaExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\TemplateExportProcessorStep'