services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\ExporterFile\Application\:
        resource: '../../Application/*'

    Ergonode\ExporterFile\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\ExporterFile\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\ExporterFile\Infrastructure\Builder\Template\:
        resource: '../../Infrastructure/Builder/Template/*'
        tags: ['export-file.template_element_map_interface']

    Ergonode\ExporterFile\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\ExporterFile\Infrastructure\Handler\ProcessExportCommandHandler:
        tags: ['messenger.message_handler']
        arguments:
            $steps:
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\AttributeExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\OptionExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\CategoryExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\ProductExportProcessStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\MultimediaExportProcessorStep'
                - '@Ergonode\ExporterFile\Infrastructure\Processor\Step\TemplateExportProcessorStep'

    Ergonode\ExporterFile\Infrastructure\Builder\TemplateElementBuilder:
       arguments:
           $builders: !tagged_iterator 'export-file.template_element_map_interface'

    Ergonode\ExporterFile\Infrastructure\Builder\ExportProductBuilder:
        arguments:
            $builders:
                - '@Ergonode\ExporterFile\Infrastructure\Builder\Product\ProductTemplateBuilder'
                - '@Ergonode\ExporterFile\Infrastructure\Builder\Product\ProductCategoryBuilder'
                - '@Ergonode\ExporterFile\Infrastructure\Builder\Product\ProductAttributeBuilder'
                - '@Ergonode\ExporterFile\Infrastructure\Builder\Product\AssociatedExportProductBuilder'
                - '@Ergonode\ExporterFile\Infrastructure\Builder\Product\VariableExportProductBuilder'