framework:
    messenger:
        routing:
            Ergonode\Category\Domain\Command\CreateCategoryCommand: '%ergonode.category.messenger_transport_name%'
            Ergonode\Category\Domain\Command\UpdateCategoryCommand: '%ergonode.category.messenger_transport_name%'
            Ergonode\Category\Domain\Command\Import\ImportCategoryCommand: '%ergonode.category.messenger_transport_name_import%'
