framework:
    messenger:
        routing:
            Ergonode\Category\Domain\Command\CreateCategoryCommand: '%ergonode.designer.messenger_transport_name%'
            Ergonode\Category\Domain\Command\UpdateCategoryCommand: '%ergonode.designer.messenger_transport_name%'
