ergonode_categeory_api:
    resource: '../../Application/Controller/Api/*'
    type: 'annotation'
    prefix: '/api/v1/{language}'

ergonode_category_tree_api:
    resource: '../../Application/Controller/Api/Tree/*'
    type: 'annotation'
    prefix: '/api/v1/{language}'

