<?php

/**
 * Copyright © Bold Brand Commerce Sp. z o.o. All rights reserved.
 * See LICENSE.txt for license details.
 */

declare(strict_types = 1);

namespace Ergonode\Comment\Domain\Entity;

use Ergonode\Core\Domain\Entity\AbstractId;

/**
 * Autogenerated class
 */
class CommentId extends AbstractId
{
}
