nelmio_api_doc:
    documentation:
        segment_definitions:
            segment:
                type: 'object'
                properties:
                    condition_set_id:
                        type: 'string'
                        required: true
                        description: 'Condition set ID'
                    code:
                        type: 'string'
                        required: true
                        description: 'Segment unique code'
                    name:
                        $ref: "#/definitions/translation"
                    description:
                        $ref: "#/definitions/translation"
                example:
                    condition_set_id: 'd1b9b64a-fef6-440c-9560-cf73daa4b4d6'
                    code: 'code'
                    name:
                        pl_PL: 'Nazwa'
                        en_GB: 'Name'
                    description:
                        pl_PL: 'Opis'
                        en_GB: 'Description'
