services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Ergonode\ImporterMagento2\Application\:
        resource: '../../Application/*'

    Ergonode\ImporterMagento2\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity}'

    Ergonode\ImporterMagento2\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\ImporterMagento2\Infrastructure\Source\Magento2ImportSource:
      arguments:
        $directory: '%import_directory%'
