framework:
    messenger:
        transports:
            completeness: "completeness://"
        routing:
            Ergonode\Completeness\Domain\Command\ProductCompletenessCalculateCommand: 'completeness'
