framework:
    messenger:
        transports:
            completeness: "completeness://"
        routing:
            Ergonode\Completeness\Domain\Command\ProductCompletenessCalculateCommand: '%ergonode.completeness.messenger_transport_name%'
