framework:
    messenger:
        transports:
            completeness: '%ergonode.completeness.messenger_transport%'
        routing:
            'Ergonode\Completeness\Domain\Command\ProductCompletenessCalculateCommand': completeness
