services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ergonode\Completeness\Application\:
    resource: '../../Application/*'

  Ergonode\Completeness\Domain\:
    resource: '../../Domain/*'
    exclude: '../../Domain/{Entity,ValueObject}'

  Ergonode\Completeness\Infrastructure\:
    resource: '../../Infrastructure/*'

  Ergonode\Completeness\Infrastructure\Handler\:
    resource: '../../Infrastructure/Handler/*'
    tags: [ 'messenger.message_handler' ]

  Ergonode\Completeness\Application\Controller\:
    resource: '../../Application/Controller/*'
    tags: [ 'controller.service_arguments' ]

  Ergonode\Completeness\Domain\Query\CompletenessQueryInterface: '@Ergonode\Completeness\Infrastructure\Persistence\Query\CompletenessQuery'

  Ergonode\Completeness\Application\Serializer\Normalizer\CompletenessReadModelNormalizer:
    $normalizer: '@Ergonode\Core\Application\Serializer\Normalizer\ObjectPropertyNormalizer'
