framework:
    messenger:
        transports:
            batch-action: "batch-action://"
        routing:
            Ergonode\BatchAction\Domain\Command\ProcessBatchActionEntryCommand: 'batch-action'
