framework:
    messenger:
        transports:
            batch_action: "batch-action://"
        routing:
            Ergonode\BatchAction\Domain\Command\ProcessBatchActionEntryCommand: 'batch_action'
