framework:
    messenger:
        routing:
            Ergonode\BatchAction\Domain\Command\StartBatchActionCommand: '%ergonode.batch_action.messenger_transport_name%'
            Ergonode\BatchAction\Domain\Command\ProcessBatchActionEntryCommand: '%ergonode.batch_action.messenger_transport_name%'
