ergonode_batch_action_api:
    resource: '../../Application/Controller/Api/*'
    type: 'annotation'
    prefix: '/api/v1/{language}'

ergonode_batch_action_notification_api:
    resource: '../../Application/Controller/Api/Notification/*'
    type: 'annotation'
    prefix: '/api/v1/{language}'
